# 爬虫

version: "2"

services:
  emailbill-spider:
    image: driver-python36
    user: root
    volumes:
      - /data/code_source/crawler/crawler_bqjr/:/work/crawler_bqjr/
      - /data/logs/crawler/:/logs/
    environment:
      - LANG=Zn_CN.UTF-8
      - LC_ALL=en_US.utf8
      - PATH=/usr/lib64/qt-3.3/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin/opt/google/chrome
    working_dir: /work/crawler_bqjr/
    command: python3 ./run_emailbill_spiders.py
