# 爬虫

version: "2"

services:
  xuexin-spider:
    image: driver-python36
    user: root
    volumes:
      - /data/code_source/crawler/crawler_bqjr/:/work/crawler_bqjr/
      - /data/logs/crawler/:/logs/
      - /data/pictures/xuexin/:/data/image_data/
    environment:
      - LANG=Zn_CN.UTF-8
      - LC_ALL=en_US.utf8
    working_dir: /work/crawler_bqjr/
    command: python3 ./run_xuexin_spiders.py
