
apiVersion: v1
kind: Service
metadata:
  labels:
    component: bqjr-crawler-rabbitmq
  name: bqjr-crawler-rabbitmq-service
  namespace: bqjr-crawler
spec:
  ports:
  - name: mq-connect
    port: 5672
    protocol: TCP
    targetPort: 5672
  selector:
    app: bqjr-crawler-rabbitmq-app
    component: bqjr-crawler-rabbitmq
  externalIPs: [10.89.1.99]