
apiVersion: v1
kind: Service
metadata:
  labels:
    component: bqjr-crawler-rabbitmq
  name: bqjr-crawler-rabbitmq-web-service
  namespace: bqjr-crawler
spec:
  ports:
  - name: mq-web
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    app: bqjr-crawler-rabbitmq-app
    component: bqjr-crawler-rabbitmq
  externalIPs: [10.89.1.99]