# 提供公共服务
#

version: "2"

services:
  mysql-master:
    image: docker.io/mysql
    volumes:
      - /data/mysql/:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=bqjr2017
      - MYSQL_USER=test
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=captchas
    command: mysqld
    user: root
